name: Run Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.7.1'  

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test 

    - name: Upload Jest Test Results to GitHub Actions
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: jest-test-results  
